version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:12-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quartz_demo
    networks:
      - tutorial
networks:
  tutorial: {}